import { currentUser } from '@clerk/nextjs/server';

export default function Page() {
  const user = currentUser();
  return (
    <div className="p-6 space-y-8 max-w-4xl">
      <section>
        <h1 className="text-4xl text-orange-400 font-bold mb-6">
          Building Your Family Story - How it works
        </h1>

        <h2 className="text-2xl font-semibold mb-4">
          Let us begin by doing one or more of the following:
        </h2>

        <div className="space-y-6">
          {/* Interview a Family Member */}
          <div>
            <h3 className="text-xl font-semibold mb-3 flex items-start">
              <span className="mr-2">•</span>
              <span>Interview a Family Member</span>
            </h3>
            <p className="ml-6 text-gray-700 leading-relaxed bg-blue-50 p-4 rounded">
              Choose a family member whose story you would like to know more
              about, obtain his/her consent, record your interview on either
              your smart phone, using zoom or any other of your choice. Do the
              interview. After doing the interview, you will review the
              interview, then please provide us with keywords and a short
              summary. Be sure to review the transcription of the interview
              after it is generated by AI and make corrections as needed.
            </p>
          </div>

          {/* Record your own story */}
          <div>
            <h3 className="text-xl font-semibold mb-3 flex items-start">
              <span className="mr-2">•</span>
              <span>Record your own story </span>
            </h3>
            <p className="ml-6 text-gray-700 leading-relaxed bg-blue-50 p-4 rounded">
              You can also record your own story. After recording your own
              story, Give your video a title and a short description. We will
              review your video and when it is approved you will be able review
              the transcript for accuracy. If you need to, you can make changes.
              When these steps are complete we can then go ahead and make your
              video available for everyone to see.You can also choose to keep
              your videos Private, to be shared only by you.
            </p>
          </div>

          {/* Upload photos or documents */}
          <div>
            <h3 className="text-xl font-semibold mb-3 flex items-start">
              <span className="mr-2">•</span>
              <span>Upload photos or documents of your family.</span>
            </h3>
            <p className="ml-6 text-gray-700 leading-relaxed bg-blue-50 p-4 rounded">
              If you have important photos and documents which can enhance your
              family story, you can upload copies and save them for future
              generations.
            </p>
          </div>
        </div>
      </section>
      {!user && (
        <section className="pt-6 border-t">
          <p className="text-gray-700">
            Please{' '}
            <a
              href="/sign-in"
              className="text-blue-600 hover:underline font-medium"
            >
              login
            </a>
            . If you have not registered, please{' '}
            <a
              href="/sign-up"
              className="text-blue-600 hover:underline font-medium"
            >
              register here
            </a>
            .
          </p>
        </section>
      )}
    </div>
  );
}
